"use client";
import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { useSession } from 'next-auth/react';
import { ArrowDownToLine, ArrowRightLeft, Boxes, ClipboardList, Download, FileSpreadsheet, Loader2, PackagePlus, Plus, QrCode, RefreshCw, ScanLine, Search, Send } from 'lucide-react';
import { AppShell, PageContainer } from './app-shell';
import { Button } from './ui/button';
import { Select, TextInput, Panel, StatusBanner } from './ui/field';
import { PhotoCapture, type CapturedPhoto } from './photo-capture';
import { QrScanner } from './qr-scanner';
import { NewProductForm } from './new-product-form';
import { QrLabels } from './qr-labels';
import { MonthlyReport } from './monthly-report';
import { postAction } from '@/lib/api-client';
import { downloadCsv } from '@/lib/csv';
import { EMPTY_CATALOGUE, groupProducts, type Catalogue } from '@/lib/catalogue';
import type { AppsScriptAction } from '@/lib/api';
import { cn } from '@/lib/utils';

interface Stock { productId:string; headOfficeAvailable:number; headOfficeBalance:number; salonFloorBalance:number; pendingHandover:number; locationBalances?:Record<string,number>; }
interface RequestRow { requestId:string; productId:string; productName:string; qty:number; status:string; source:string; notes:string; }
interface Handover { handoverId:string; productId:string; productName:string; qty:number; uom:string; actor:string; notes:string; toLocationId?:string; }
interface Order { orderId:string; productId:string; productName:string; vendorId:string; qty:number; received:number; remaining:number; uom:string; status:string; }
interface History { txnId:string; date:string; productId:string; qty:number; uom:string; type:string; locationId:string; personId:string; status:string; notes:string; }
interface Data { myLocationId?:string; catalogue:Catalogue; dashboard:{stock:Stock[];openRequests:RequestRow[];pendingHandovers:Handover[]};orders:Order[];history:History[]; }
type Tab='product'|'labels'|'report'|'stock'|'requests'|'deliveries'|'handovers'|'issue'|'history';
type Kind='request'|'order'|'receive'|'handover'|'issue'|'correction';
interface FormSpec { kind:Kind; productId?:string; orderId?:string; requestId?:string; }
const TABS=[{id:'product',label:'New product',icon:PackagePlus},{id:'stock',label:'My stock',icon:Boxes},{id:'requests',label:'Requests',icon:ClipboardList},{id:'deliveries',label:'Purchases',icon:ArrowDownToLine},{id:'handovers',label:'Handovers',icon:ArrowRightLeft},{id:'issue',label:'Issue stock',icon:Send},{id:'history',label:'History',icon:ClipboardList},{id:'labels',label:'QR labels',icon:QrCode},{id:'report',label:'Monthly report',icon:FileSpreadsheet}] as const;
const LABEL:Record<Kind,string>={request:'Request stock',order:'Create purchase order',receive:'Record delivery',handover:'Send to a studio',issue:'Issue to technician',correction:'Record correction'};
function Status({value}:{value:string}){return <span className={cn('inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold tracking-wide',/PENDING|PARTIAL|OPEN|ORDERED/.test(value)?'bg-amber-50 text-amber-800':/REJECT|VOID|CANCEL/.test(value)?'bg-red-50 text-red-700':'bg-teal-50 text-teal-800')}>{value.replaceAll('_',' ')}</span>;}
function Empty({text}:{text:string}){return <div className="flex flex-col items-center gap-3 px-6 py-12 text-center"><Boxes className="size-8 text-muted-foreground/50"/><p className="max-w-sm text-sm text-muted-foreground">{text}</p></div>;}
function Section({title,description,button,onClick,disabled}:{title:string;description:string;button?:string;onClick?:()=>void;disabled?:boolean}){return <div className="flex flex-wrap items-start justify-between gap-3 border-b p-5"><div><h2 className="font-semibold">{title}</h2><p className="mt-1 max-w-lg text-xs leading-relaxed text-muted-foreground">{description}</p></div>{button&&<Button variant="outline" disabled={disabled} onClick={onClick}>{button==='Export CSV'?<Download className="size-4"/>:<Plus className="size-4"/>}{button}</Button>}</div>;}
function Field({title,wide,children}:{title:string;wide?:boolean;children:ReactNode}){return <label className={cn('grid min-w-0 gap-2 text-sm',wide&&'sm:col-span-2')}>{title}{children}</label>;}

export function OperationsHub({office}:{office:boolean}) {
  const {data:session}=useSession(),admin=session?.user.role==='Admin';
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<Tab>('stock');
  const [search,setSearch]=useState(''),[type,setType]=useState(''),[availableOnly,setAvailableOnly]=useState(false),[form,setForm]=useState<FormSpec|null>(null),[preset,setPreset]=useState<{id:string;n:number}|null>(null);
  const [recounts,setRecounts]=useState<Record<string,string>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[online,setOnline]=useState(true);
  const c=data?.catalogue||EMPTY_CATALOGUE,loc=office?c.headOfficeLocationId:(data?.myLocationId||c.salonFloorLocationId),locationName=office?'Head Office':(c.locations.find(l=>l.id===loc)?.name||'Salon Floor');
  const load=useCallback(async()=>{setLoading(true);setError('');const r=await postAction<Data>('operations.read',{});setLoading(false);if(r.ok)setData(r.data);else{setError(r.message);setData(null);}},[]);
  useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);},[load]);
  useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync);};},[]);
  const perform=async(action:AppsScriptAction,values:object)=>{if(busy||!online)return false;setBusy(true);setNotice('');setError('');const r=await postAction(action,values);setBusy(false);if(r.ok){setNotice('Saved successfully. Stock and pending work have been refreshed.');setForm(null);await load();return true;}setError(r.message);return false;};
  const catLabel=(id:string)=>{const k=c.categories.find(x=>x.id===id);return k?`${k.name}${k.unit?` (${k.unit})`:''}`:'';};
  const balance=(id:string)=>{const s=data?.dashboard.stock.find(s=>s.productId===id);return (office?s?.headOfficeAvailable:(s?.locationBalances?.[loc]??s?.salonFloorBalance))||0;};
  const products=c.products.filter(p=>(!type||p.productType===type)&&p.name.toLowerCase().includes(search.toLowerCase())&&(!availableOnly||balance(p.id)>0)).sort((a,b)=>Number(balance(b.id)>0)-Number(balance(a.id)>0)||a.name.localeCompare(b.name));
  const pending=data?.dashboard.pendingHandovers||[],history=(data?.history||[]).filter(h=>h.locationId===loc);
  const exportHistory=()=>downloadCsv([['Date','Product','Type','Qty','Unit','Person','Status','Notes'],...history.map(h=>[h.date,c.products.find(p=>p.id===h.productId)?.name||h.productId,h.type,h.qty,h.uom,c.people.find(p=>p.id===h.personId)?.name||h.personId,h.status,h.notes])],`ahl-${office?'head-office':'salon-floor'}-history.csv`);
  const noteField=(id:string,title:string)=><Field title={title}><TextInput value={notes[id]||''} onChange={e=>setNotes({...notes,[id]:e.target.value})}/></Field>;
  return <AppShell><PageContainer className="pb-12">
    <div className="flex flex-wrap items-end justify-between gap-4 py-7 sm:py-9"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-brand">AHL · {locationName}</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{office?'Purchase & inventory':'Salon inventory'}</h1><p className="mt-2 text-sm text-muted-foreground">{office?'Know what arrived, what is available, and where it goes.':'Receive, count and issue stock with confidence.'}</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading||busy}><RefreshCw className={cn('size-4',loading&&'animate-spin')}/>{loading?'Loading':'Refresh'}</Button></div>
    {!online&&<StatusBanner tone="error" title="You are offline">Reconnect before recording stock movements.</StatusBanner>}{error&&<div className="mb-4"><StatusBanner tone="error" title="Action needs attention">{error}</StatusBanner></div>}{notice&&<div className="mb-4"><StatusBanner tone="success">{notice}</StatusBanner></div>}
    <div className="mb-6 grid grid-cols-3 gap-2 sm:gap-3">{[['Products available',data?data.dashboard.stock.filter(s=>(office?s.headOfficeAvailable:s.salonFloorBalance)>0).length:'—'],['Waiting for receipt',data?pending.length:'—'],['Open requests',data?data.dashboard.openRequests.length:'—']].map(([label,value])=><div key={label} className="rounded-2xl border border-border bg-card p-4 sm:p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular">{value}</p></div>)}</div>
    <div className="grid items-start gap-5 lg:grid-cols-[190px_1fr]"><nav aria-label="Inventory tasks" className="-mx-4 flex gap-1.5 overflow-x-auto border-y border-border bg-card p-2 sm:mx-0 sm:rounded-2xl sm:border lg:sticky lg:top-20 lg:grid lg:grid-cols-1 lg:overflow-visible">{TABS.filter(t=>office||!['deliveries','product','labels','report'].includes(t.id)).map(t=><button key={t.id} onClick={()=>{setTab(t.id);setForm(null);setNotice('');}} aria-current={tab===t.id?'page':undefined} className={cn('flex min-h-11 shrink-0 items-center gap-2 whitespace-nowrap rounded-xl px-3 py-2.5 text-left text-sm font-medium transition-colors',tab===t.id?'bg-brand text-white':'text-muted-foreground hover:bg-muted')}><t.icon className="size-4 shrink-0"/>{t.label}</button>)}</nav>
    <div className="min-w-0 space-y-4">{form&&data?<StockForm key={JSON.stringify(form)} form={form} data={data} office={office} admin={admin} busy={busy||loading||!online} onSubmit={perform} onClose={()=>setForm(null)}/>:<>
      {tab==='product'&&office&&<NewProductForm catalogue={c} onCreated={()=>void load()} onPrintLabel={id=>{setPreset({id,n:1});setTab('labels');}}/>}
      {tab==='labels'&&office&&<QrLabels key={preset?.id} products={c.products} preset={preset}/>}
      {tab==='report'&&office&&<MonthlyReport/>}
      {tab==='stock'&&<Panel><Section title={`Available in ${locationName}`} description="Products in stock appear first." button="Correction" disabled={!data} onClick={()=>setForm({kind:'correction'})}/><div className="space-y-3 border-b p-5"><div className="grid gap-3 sm:grid-cols-[1fr_160px]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground"/><TextInput aria-label="Search products" placeholder="Search products…" className="pl-9" value={search} onChange={e=>setSearch(e.target.value)}/></label><Select aria-label="Product type" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{['Consumable','Retail','Both'].map(t=><option key={t}>{t}</option>)}</Select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={availableOnly} onChange={e=>setAvailableOnly(e.target.checked)}/>In stock only</label></div>{loading?<Empty text="Loading your live inventory…"/>:!products.length?<Empty text="No matching products. Refresh or change the filters."/>:<ul className="divide-y">{products.map(p=><li key={p.id} className="flex items-center gap-3 p-4 sm:px-5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-muted"><Boxes className="size-5 text-brand"/></span><div className="min-w-0 flex-1"><p className="text-sm font-medium break-words">{p.name}</p><p className="mt-1 text-xs text-muted-foreground">{p.productType} · {p.uom}{catLabel(p.categoryId)&&` · ${catLabel(p.categoryId)}`}</p></div><div className="text-right"><p className="text-lg font-semibold tabular">{balance(p.id)}</p><button disabled={balance(p.id)<=0} className="min-h-8 text-xs font-semibold text-brand disabled:opacity-40" onClick={()=>setForm({kind:'issue',productId:p.id})}>Issue</button></div></li>)}</ul>}</Panel>}
      {tab==='requests'&&<Panel><Section title="Stock requests" description="Track requests from the app, WhatsApp or a call." button="New request" disabled={!data} onClick={()=>setForm({kind:'request'})}/>{!data?.dashboard.openRequests.length?<Empty text="No open requests."/>:<ul className="divide-y">{data.dashboard.openRequests.map(r=><li key={r.requestId} className="space-y-3 p-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{r.productName} · {r.qty}</p><Status value={r.status}/></div><p className="text-xs text-muted-foreground">{r.source||'APP'} · {r.notes}</p>{office&&<div className="flex flex-wrap gap-2">{r.status==='PENDING_APPROVAL'?<><Button disabled={busy} onClick={()=>void perform('purchase.approve',{requestId:r.requestId,decision:'APPROVE'})}>Approve</Button><Button disabled={busy} variant="outline" onClick={()=>void perform('purchase.approve',{requestId:r.requestId,decision:'REJECT'})}>Reject</Button></>:r.productId&&<><Button variant="outline" onClick={()=>setForm({kind:'order',productId:r.productId,requestId:r.requestId})}>Order from vendor</Button><Button variant="outline" onClick={()=>setForm({kind:'handover',productId:r.productId,requestId:r.requestId})}>Supply from stock</Button></>}</div>}</li>)}</ul>}</Panel>}
      {tab==='deliveries'&&<Panel><Section title="Purchases & deliveries" description="Only actual receipts increase stock. Opening stock is recorded separately." button="New purchase" disabled={!data} onClick={()=>setForm({kind:'order'})}/><div className="px-5 pt-4"><Button variant="outline" disabled={!data} onClick={()=>setForm({kind:'receive'})}>Delivery without an order</Button></div>{!data?.orders.length?<Empty text="No purchase orders recorded yet."/>:<ul className="divide-y">{data.orders.map(o=><li key={o.orderId} className="space-y-3 p-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{o.productName}</p><Status value={o.status}/></div><p className="text-xs text-muted-foreground">{o.orderId} · {c.vendors.find(v=>v.id===o.vendorId)?.name}{o.received>0&&<> · <button className="font-semibold text-brand" onClick={()=>{setPreset({id:o.productId,n:Math.ceil(o.received)});setTab('labels');}}>Print labels</button></>}</p><div className="grid grid-cols-3 gap-2 text-sm"><span>Ordered <strong>{o.qty}</strong></span><span>Received <strong>{o.received}</strong></span><span>Due <strong>{o.remaining} {o.uom}</strong></span></div>{o.remaining>0&&o.status!=='CANCELLED'&&<><Button disabled={busy} onClick={()=>setForm({kind:'receive',productId:o.productId,orderId:o.orderId})}>Receive delivery</Button>{noteField(o.orderId,'Reason to cancel remaining order')}<Button variant="outline" disabled={busy||!notes[o.orderId]} onClick={()=>void perform('order.cancel',{orderId:o.orderId,notes:notes[o.orderId]})}>Cancel remaining order</Button></>}</li>)}</ul>}</Panel>}
      {tab==='handovers'&&<Panel><Section title={office?'Sent to studios':'Confirm incoming stock'} description={office?'Pending quantities are reserved until the receiver confirms.':'Count the physical pieces before confirming receipt.'} button={office?'New handover':undefined} disabled={!data} onClick={()=>setForm({kind:'handover'})}/>{!pending.length?<Empty text="No handovers awaiting confirmation."/>:<ul className="divide-y">{pending.map(h=><li key={h.handoverId} className="space-y-3 p-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{h.productName} · {h.qty} {h.uom}</p><Status value="PENDING_CONFIRM"/></div>{office&&h.toLocationId&&<p className="text-xs text-muted-foreground">To {c.locations.find(l=>l.id===h.toLocationId)?.name||h.toLocationId}</p>}<p className="text-xs text-muted-foreground break-words">{h.notes}</p>{!office&&<Field title="Quantity you counted"><TextInput type="number" min="0" step="any" value={recounts[h.handoverId]??''} onChange={e=>setRecounts({...recounts,[h.handoverId]:e.target.value})}/></Field>}{noteField(h.handoverId,office?'Reason for cancellation':'Note / count difference')}{office?<Button variant="outline" disabled={busy||!notes[h.handoverId]} onClick={()=>void perform('handover.cancel',{handoverId:h.handoverId,notes:notes[h.handoverId]})}>Cancel & release reservation</Button>:<Button disabled={busy||!online||!recounts[h.handoverId]} onClick={()=>void perform('stock.confirmHandover',{handoverId:h.handoverId,countedQty:Number(recounts[h.handoverId]),notes:notes[h.handoverId]||''})}>Confirm my count</Button>}<p className="text-xs text-muted-foreground">A different count keeps this pending. Agree the correction, then the sender can cancel and send a corrected handover.</p></li>)}</ul>}</Panel>}
      {tab==='issue'&&data&&<StockForm key={tab} form={{kind:'issue'}} data={data} office={office} admin={admin} busy={busy||loading||!online} onSubmit={perform}/>}
      {tab==='history'&&<Panel><Section title="Movement history" description="Recent 500 movements across locations; this view shows your location." button="Export CSV" disabled={!history.length} onClick={exportHistory}/>{!history.length?<Empty text="Posted receipts, issues and corrections will appear here."/>:<ul className="divide-y">{history.map(h=><li key={h.txnId} className="space-y-2 p-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-medium">{c.products.find(p=>p.id===h.productId)?.name||h.productId} · {h.qty} {h.uom}</p><Status value={h.type}/></div><p className="text-xs text-muted-foreground">{new Date(h.date).toLocaleDateString('en-IN')} · {h.status} · {c.people.find(p=>p.id===h.personId)?.name||h.personId}</p><p className="text-xs break-words">{h.notes}</p></li>)}</ul>}</Panel>}
    </>}</div></div>
  </PageContainer></AppShell>;
}

function StockForm({form,data,office,admin,busy,onSubmit,onClose}:{form:FormSpec;data:Data;office:boolean;admin:boolean;busy:boolean;onSubmit:(action:AppsScriptAction,data:object)=>Promise<boolean>;onClose?:()=>void}) {
  const c=data.catalogue,kind=form.kind;
  const [productId,setProductId]=useState(form.productId||''),[qty,setQty]=useState(''),[person,setPerson]=useState(''),[category,setCategory]=useState(''),[businessUnit,setBusinessUnit]=useState(''),[vendor,setVendor]=useState(data.orders.find(o=>o.orderId===form.orderId)?.vendorId||''),[note,setNote]=useState(''),[search,setSearch]=useState(''),[makeMain,setMakeMain]=useState(false);
  const [toLocation,setToLocation]=useState(c.salonFloorLocationId);
  const [source,setSource]=useState('APP'),[newName,setNewName]=useState(''),[approvedBy,setApprovedBy]=useState(''),[urgency,setUrgency]=useState('Normal'),[estimate,setEstimate]=useState(''),[correction,setCorrection]=useState('RETURN'),[sourceTxnId,setSourceTxnId]=useState('');
  const [invoice,setInvoice]=useState(''),[amount,setAmount]=useState(''),[photo,setPhoto]=useState<CapturedPhoto|null>(null),[productPhoto,setProductPhoto]=useState<CapturedPhoto|null>(null);
  const [scanning,setScanning]=useState(false),[scanError,setScanError]=useState('');
  const p=c.products.find(p=>p.id===productId),s=data.dashboard.stock.find(s=>s.productId===productId),loc=office?c.headOfficeLocationId:(data.myLocationId||c.salonFloorLocationId),available=(office?s?.headOfficeAvailable:(s?.locationBalances?.[loc]??s?.salonFloorBalance))||0;
  const uom=kind==='receive'||kind==='order'?p?.purchaseUom:p?.uom,requiresPerson=['request','handover','issue'].includes(kind),people=c.people.filter(p=>kind!=='handover'||(p.role==='ProductDistributor'&&(toLocation===c.salonFloorLocationId||p.locationId===toLocation)));
  const studios=c.locations.filter(l=>l.unit&&l.id!==c.headOfficeLocationId&&(l.id===c.salonFloorLocationId||c.people.some(p=>p.role==='ProductDistributor'&&p.locationId===l.id)));
  const products=c.products,byVendor=kind==='order'||kind==='receive';
  const handleScan=(code:string)=>{const match=products.find(p=>p.id===code);if(match){setProductId(match.id);setScanning(false);setScanError('');}else{setScanError("That code doesn't match a product you can issue.");}};
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const common={productId,qty:Number(qty),notes:note};const action:AppsScriptAction=({request:'purchase.request',order:'order.create',receive:'stock.receive',handover:'stock.handover',issue:'stock.issue',correction:'stock.adjust'} as const)[kind];let values:object=common;
    if(kind==='request')values={...common,newProductName:newName,requestedByUserId:person,source,urgency,estimatedValue:estimate?Number(estimate):undefined,approvedBy};
    if(kind==='order')values={...common,vendorId:vendor,requestId:form.requestId||''};
    if(kind==='receive')values={...common,vendorId:vendor,poId:form.orderId||'',invoiceNo:invoice,amount:amount?Number(amount):undefined,receivedByUserId:person,locationId:c.headOfficeLocationId,photo,productPhoto};
    if(kind==='handover')values={...common,toUserId:person,toLocationId:toLocation,requestId:form.requestId||''};
    if(kind==='issue')values={productId,fromLocationId:loc,splits:[{qty:Number(qty),recipientUserId:person,categoryId:category,businessUnit,notes:note}]};
    if(kind==='correction')values={...common,locationId:loc,kind:correction,sourceTxnId};
    if(await onSubmit(action,values)){if(byVendor&&makeMain&&vendor)void postAction('product.setVendor',{productId,vendorId:vendor});setSearch('');setMakeMain(false);setQty('');setNote('');setProductId('');setBusinessUnit('');setPhoto(null);setProductPhoto(null);}
  };
  return <Panel><Section title={LABEL[kind]} description={kind==='issue'?`Deducts from ${office?'Head Office':'Salon Floor'} stock.`:kind==='order'?'Creating an order does not change available stock.':kind==='handover'?'Stock stays reserved at Head Office until the receiver at the studio counts and confirms.':kind==='receive'?'Enter only the quantity that actually arrived.':'Every movement keeps a reference and reason.'}/><form onSubmit={submit} className="p-5 sm:p-6"><fieldset disabled={busy} className="grid min-w-0 gap-5 sm:grid-cols-2 disabled:opacity-60">
    {(kind==='issue'||kind==='handover')&&scanning&&<div className="sm:col-span-2"><QrScanner onDecode={handleScan} onClose={()=>setScanning(false)}/></div>}
    {(kind==='issue'||kind==='handover')&&!scanning&&scanError&&<p className="rounded-xl bg-danger-subtle p-3 text-sm text-danger sm:col-span-2">{scanError}</p>}
    {kind==='handover'&&<Field title="Send to" wide><Select value={toLocation} onChange={e=>{setToLocation(e.target.value);setPerson('');}}>{studios.map(l=><option key={l.id} value={l.id}>{l.name} ({l.unit})</option>)}</Select></Field>}
    {['order','receive'].includes(kind)&&<Field title="Vendor" wide><Select required disabled={!!form.orderId} value={vendor} onChange={e=>{setVendor(e.target.value);setMakeMain(false);}}><option value="">Select vendor</option>{c.vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</Select></Field>}
    {(byVendor||kind==='request')&&!form.orderId&&<Field title="Search product" wide><TextInput value={search} onChange={e=>setSearch(e.target.value)} placeholder="Type a name; matches move to the top of the list"/></Field>}
    <Field title="Product" wide><div className="flex gap-2"><Select required={!newName} value={productId} disabled={!!form.orderId||!!newName} onChange={e=>{setProductId(e.target.value);setScanError('');}}><option value="">Select product</option>{groupProducts(products,c.vendors,byVendor?vendor:'',search).map(g=><optgroup key={g.label} label={g.label}>{g.items.map(p=><option key={p.id} value={p.id}>{p.name} ({byVendor?p.purchaseUom:p.uom})</option>)}</optgroup>)}</Select>{(kind==='issue'||kind==='handover')&&!scanning&&<Button type="button" variant="outline" onClick={()=>{setScanning(true);setScanError('');}}><ScanLine className="size-4"/>Scan</Button>}</div></Field>
    {byVendor&&p&&vendor&&p.vendorId!==vendor&&<label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={makeMain} onChange={e=>setMakeMain(e.target.checked)}/>{p.vendorId?`Change main vendor of this product to ${c.vendors.find(v=>v.id===vendor)?.name}`:`Set ${c.vendors.find(v=>v.id===vendor)?.name} as main vendor of this product`}</label>}
    {kind==='request'&&<Field title="New product name (only if absent above)" wide><TextInput disabled={!!productId} value={newName} onChange={e=>setNewName(e.target.value)}/></Field>}
    {p&&['issue','handover'].includes(kind)&&<p className="rounded-xl bg-brand-subtle p-3 text-sm text-brand sm:col-span-2">Available: <strong>{available} {p.uom}</strong></p>}
    <Field title={`${kind==='receive'?'Quantity received':'Quantity'} ${uom?'('+uom+')':''}`}><TextInput required type="number" min={uom==='PCS'?1:0.001} step={uom==='PCS'?1:'any'} value={qty} onChange={e=>setQty(e.target.value)} max={['issue','handover','office'].includes(kind)?available:undefined}/></Field>
    {(requiresPerson||kind==='receive')&&<Field title={kind==='handover'?`Receiver at ${studios.find(l=>l.id===toLocation)?.name||'studio'}`:kind==='request'?'Requested by':kind==='receive'?'Received by (optional)':'Technician'}><Select required={requiresPerson} value={person} onChange={e=>setPerson(e.target.value)}><option value="">Select person</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field>}
    {kind==='issue'&&<Field title="Service / category"><Select required value={category} onChange={e=>{setCategory(e.target.value);setBusinessUnit(c.categories.find(x=>x.id===e.target.value)?.unit||'');}}><option value="">Select category</option>{c.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field>}
    {kind==='issue'&&<Field title="Used by (business unit)"><Select required value={businessUnit} onChange={e=>setBusinessUnit(e.target.value)}><option value="">Select business unit</option>{['AHL','Alchemane','Shared'].map(u=><option key={u}>{u}</option>)}</Select><span className="text-xs text-muted-foreground">Suggested from the category. Change it if another company used this stock. Issue again for the rest.</span></Field>}
    {kind==='request'&&<><Field title="Request source"><Select value={source} onChange={e=>setSource(e.target.value)}>{['APP','WHATSAPP','CALL'].map(s=><option key={s}>{s}</option>)}</Select></Field><Field title="Priority"><Select value={urgency} onChange={e=>setUrgency(e.target.value)}><option>Normal</option><option>Urgent</option></Select></Field><Field title="Estimated value (₹, optional)"><TextInput type="number" min="0" value={estimate} onChange={e=>setEstimate(e.target.value)}/></Field>{office&&<Field title={`Approved by (required from ₹${c.approvalThreshold})`}><TextInput value={approvedBy} onChange={e=>setApprovedBy(e.target.value)}/></Field>}</>}
    {kind==='receive'&&<><Field title="Invoice number"><TextInput value={invoice} onChange={e=>setInvoice(e.target.value)}/></Field><Field title="Amount for this product line (₹)"><TextInput type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><div className="sm:col-span-2"><p className="mb-2 text-sm">Bill photo</p><PhotoCapture onCapture={setPhoto} disabled={busy}/></div><div className="sm:col-span-2"><p className="mb-2 text-sm">Product photo (optional)</p><PhotoCapture onCapture={setProductPhoto} disabled={busy}/></div></>}
    {kind==='correction'&&<><Field title="Correction type"><Select value={correction} onChange={e=>setCorrection(e.target.value)}><option value="RETURN">Unused stock returned by technician</option><option value="DAMAGE">Damaged stock</option>{admin&&<><option value="COUNT_IN">Count adjustment — increase</option><option value="COUNT_OUT">Count adjustment — decrease</option></>}</Select></Field>{correction==='RETURN'&&<Field title="Original issue" wide><Select required value={sourceTxnId} onChange={e=>setSourceTxnId(e.target.value)}><option value="">Select issue</option>{data.history.filter(h=>h.type==='ISSUE'&&h.productId===productId&&h.locationId===loc&&h.status!=='VOID').map(h=><option key={h.txnId} value={h.txnId}>{h.txnId} · {h.qty} {h.uom}</option>)}</Select></Field>}</>}
    <Field title={kind==='request'||kind==='correction'?'Reason':'Note (optional)'} wide><TextInput required={kind==='request'||kind==='correction'} minLength={kind==='request'?3:undefined} value={note} onChange={e=>setNote(e.target.value)} placeholder="Purpose, shelf, room or details"/></Field><div className="flex flex-wrap gap-3 border-t pt-5 sm:col-span-2"><Button type="submit" className="min-h-11 flex-1 sm:flex-none" disabled={busy}>{busy&&<Loader2 className="size-4 animate-spin"/>}{LABEL[kind]}</Button>{onClose&&<Button type="button" variant="outline" onClick={onClose}>Cancel</Button>}</div>
  </fieldset></form></Panel>;
}
