"use client";
import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { useSession } from 'next-auth/react';
import { ArrowDownToLine, ArrowRightLeft, Boxes, ClipboardList, Download, Loader2, PackageCheck, Plus, RefreshCw, Search, Send, Settings2 } from 'lucide-react';
import { AppShell, PageContainer } from './app-shell';
import { Button } from './ui/button';
import { Select, TextInput, Panel, StatusBanner } from './ui/field';
import { PhotoCapture, type CapturedPhoto } from './photo-capture';
import { postAction } from '@/lib/api-client';
import { EMPTY_CATALOGUE, type Catalogue } from '@/lib/catalogue';
import type { AppsScriptAction } from '@/lib/api';
import { cn } from '@/lib/utils';

interface Stock { productId:string; headOfficeAvailable:number; headOfficeBalance:number; salonFloorBalance:number; pendingHandover:number; }
interface RequestRow { requestId:string; productId:string; productName:string; qty:number; status:string; source:string; notes:string; }
interface Handover { handoverId:string; productId:string; productName:string; qty:number; uom:string; actor:string; notes:string; }
interface Opening { countId:string; productId:string; productName:string; qty:number; uom:string; status:string; locationId:string; }
interface Order { orderId:string; productId:string; productName:string; vendorId:string; qty:number; received:number; remaining:number; uom:string; status:string; }
interface History { txnId:string; date:string; productId:string; qty:number; uom:string; type:string; locationId:string; personId:string; status:string; notes:string; }
interface Asset { assignmentId:string; productName:string; qty:number; uom:string; assignedTo:string; }
interface Data { catalogue:Catalogue; dashboard:{stock:Stock[];openRequests:RequestRow[];pendingHandovers:Handover[];assetsInUse:Asset[]};orders:Order[];opening:Opening[];history:History[]; }
type Tab='stock'|'requests'|'deliveries'|'handovers'|'issue'|'office'|'opening'|'history';
type Kind='request'|'order'|'receive'|'handover'|'issue'|'office'|'opening'|'correction';
interface FormSpec { kind:Kind; productId?:string; orderId?:string; requestId?:string; }
const TABS=[{id:'stock',label:'My stock',icon:Boxes},{id:'requests',label:'Requests',icon:ClipboardList},{id:'deliveries',label:'Purchases',icon:ArrowDownToLine},{id:'handovers',label:'Handovers',icon:ArrowRightLeft},{id:'issue',label:'Issue stock',icon:Send},{id:'office',label:'Office use',icon:Settings2},{id:'opening',label:'Opening stock',icon:PackageCheck},{id:'history',label:'History',icon:ClipboardList}] as const;
const LABEL:Record<Kind,string>={request:'Request stock',order:'Create purchase order',receive:'Record delivery',handover:'Send to Salon Floor',issue:'Issue to technician',office:'Assign office equipment',opening:'Record opening stock',correction:'Record correction'};
function Status({value}:{value:string}){return <span className={cn('inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold tracking-wide',/PENDING|PARTIAL|OPEN|ORDERED/.test(value)?'bg-amber-50 text-amber-800':/REJECT|VOID|CANCEL/.test(value)?'bg-red-50 text-red-700':'bg-teal-50 text-teal-800')}>{value.replaceAll('_',' ')}</span>;}
function Empty({text}:{text:string}){return <div className="flex flex-col items-center gap-3 px-6 py-12 text-center"><Boxes className="size-8 text-muted-foreground/50"/><p className="max-w-sm text-sm text-muted-foreground">{text}</p></div>;}
function Section({title,description,button,onClick,disabled}:{title:string;description:string;button?:string;onClick?:()=>void;disabled?:boolean}){return <div className="flex flex-wrap items-start justify-between gap-3 border-b p-5"><div><h2 className="font-semibold">{title}</h2><p className="mt-1 max-w-lg text-xs leading-relaxed text-muted-foreground">{description}</p></div>{button&&<Button variant="outline" disabled={disabled} onClick={onClick}>{button==='Export CSV'?<Download className="size-4"/>:<Plus className="size-4"/>}{button}</Button>}</div>;}
function Field({title,wide,children}:{title:string;wide?:boolean;children:ReactNode}){return <label className={cn('grid min-w-0 gap-2 text-sm',wide&&'sm:col-span-2')}>{title}{children}</label>;}

export function OperationsHub({office}:{office:boolean}) {
  const {data:session}=useSession(),admin=session?.user.role==='Admin';
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<Tab>('stock');
  const [search,setSearch]=useState(''),[type,setType]=useState(''),[availableOnly,setAvailableOnly]=useState(false),[form,setForm]=useState<FormSpec|null>(null);
  const [recounts,setRecounts]=useState<Record<string,string>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[online,setOnline]=useState(true);
  const c=data?.catalogue||EMPTY_CATALOGUE,loc=office?c.headOfficeLocationId:c.salonFloorLocationId,locationName=office?'Head Office':'Salon Floor';
  const load=useCallback(async()=>{setLoading(true);setError('');const r=await postAction<Data>('operations.read',{});setLoading(false);if(r.ok)setData(r.data);else{setError(r.message);setData(null);}},[]);
  useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);},[load]);
  useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync);};},[]);
  const perform=async(action:AppsScriptAction,values:object)=>{if(busy||!online)return false;setBusy(true);setNotice('');setError('');const r=await postAction(action,values);setBusy(false);if(r.ok){setNotice('Saved successfully. Stock and pending work have been refreshed.');setForm(null);await load();return true;}setError(r.message);return false;};
  const balance=(id:string)=>{const s=data?.dashboard.stock.find(s=>s.productId===id);return (office?s?.headOfficeAvailable:s?.salonFloorBalance)||0;};
  const products=c.products.filter(p=>(!type||p.productType===type)&&p.name.toLowerCase().includes(search.toLowerCase())&&(!availableOnly||balance(p.id)>0)).sort((a,b)=>Number(balance(b.id)>0)-Number(balance(a.id)>0)||a.name.localeCompare(b.name));
  const openings=(data?.opening||[]).filter(o=>o.locationId===loc),pending=data?.dashboard.pendingHandovers||[],history=(data?.history||[]).filter(h=>h.locationId===loc);
  const exportHistory=()=>{const safe=(v:unknown)=>{const s=String(v??'');return '"'+(/^[=+@\-\t\r]/.test(s)?"'":'')+s.replaceAll('"','""')+'"';};const csv=[['Date','Product','Type','Qty','Unit','Person','Status','Notes'],...history.map(h=>[h.date,c.products.find(p=>p.id===h.productId)?.name||h.productId,h.type,h.qty,h.uom,c.people.find(p=>p.id===h.personId)?.name||h.personId,h.status,h.notes])].map(r=>r.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`ahl-${office?'head-office':'salon-floor'}-history.csv`;a.click();URL.revokeObjectURL(url);};
  const noteField=(id:string,title:string)=><Field title={title}><TextInput value={notes[id]||''} onChange={e=>setNotes({...notes,[id]:e.target.value})}/></Field>;
  return <AppShell><PageContainer className="pb-12">
    <div className="flex flex-wrap items-end justify-between gap-4 py-7 sm:py-9"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-brand">AHL · {locationName}</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{office?'Purchase & inventory':'Salon inventory'}</h1><p className="mt-2 text-sm text-muted-foreground">{office?'Know what arrived, what is available, and where it goes.':'Receive, count and issue stock with confidence.'}</p></div><Button variant="outline" onClick={()=>void load()} disabled={loading||busy}><RefreshCw className={cn('size-4',loading&&'animate-spin')}/>{loading?'Loading':'Refresh'}</Button></div>
    {!online&&<StatusBanner tone="error" title="You are offline">Reconnect before recording stock movements.</StatusBanner>}{error&&<div className="mb-4"><StatusBanner tone="error" title="Action needs attention">{error}</StatusBanner></div>}{notice&&<div className="mb-4"><StatusBanner tone="success">{notice}</StatusBanner></div>}
    <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Products available',data?data.dashboard.stock.filter(s=>(office?s.headOfficeAvailable:s.salonFloorBalance)>0).length:'—'],['Waiting for receipt',data?pending.length:'—'],['Open requests',data?data.dashboard.openRequests.length:'—'],['Opening counts pending',data?openings.filter(o=>o.status==='PENDING').length:'—']].map(([label,value])=><div key={label} className="rounded-2xl border border-border bg-card p-4 sm:p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular">{value}</p></div>)}</div>
    <div className="grid items-start gap-5 lg:grid-cols-[190px_1fr]"><nav aria-label="Inventory tasks" className="grid grid-cols-2 gap-1.5 rounded-2xl border border-border bg-card p-2 sm:grid-cols-4 lg:sticky lg:top-20 lg:grid-cols-1">{TABS.filter(t=>office||!['deliveries','office'].includes(t.id)).map(t=><button key={t.id} onClick={()=>{setTab(t.id);setForm(null);setNotice('');}} aria-current={tab===t.id?'page':undefined} className={cn('flex min-h-11 items-center gap-2 rounded-xl px-3 py-2.5 text-left text-sm font-medium transition-colors',tab===t.id?'bg-brand text-white':'text-muted-foreground hover:bg-muted')}><t.icon className="size-4 shrink-0"/>{t.label}</button>)}</nav>
    <div className="min-w-0 space-y-4">{form&&data?<StockForm key={JSON.stringify(form)} form={form} data={data} office={office} admin={admin} busy={busy||loading||!online} onSubmit={perform} onClose={()=>setForm(null)}/>:<>
      {tab==='stock'&&<Panel><Section title={`Available in ${locationName}`} description="Products in stock appear first. Pending opening counts are excluded." button="Correction" disabled={!data} onClick={()=>setForm({kind:'correction'})}/><div className="space-y-3 border-b p-5"><div className="grid gap-3 sm:grid-cols-[1fr_160px]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground"/><TextInput aria-label="Search products" placeholder="Search products…" className="pl-9" value={search} onChange={e=>setSearch(e.target.value)}/></label><Select aria-label="Product type" value={type} onChange={e=>setType(e.target.value)}><option value="">All types</option>{['Consumable','Retail','Furniture'].map(t=><option key={t}>{t}</option>)}</Select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={availableOnly} onChange={e=>setAvailableOnly(e.target.checked)}/>In stock only</label></div>{loading?<Empty text="Loading your live inventory…"/>:!products.length?<Empty text="No matching products. Refresh or change the filters."/>:<ul className="divide-y">{products.map(p=><li key={p.id} className="flex items-center gap-3 p-4 sm:px-5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-muted"><Boxes className="size-5 text-brand"/></span><div className="min-w-0 flex-1"><p className="text-sm font-medium break-words">{p.name}</p><p className="mt-1 text-xs text-muted-foreground">{p.productType} · {p.uom}</p></div><div className="text-right"><p className="text-lg font-semibold tabular">{balance(p.id)}</p><button disabled={balance(p.id)<=0||(!office&&p.productType==='Furniture')} className="min-h-8 text-xs font-semibold text-brand disabled:opacity-40" onClick={()=>setForm({kind:p.productType==='Furniture'?'office':'issue',productId:p.id})}>Issue</button></div></li>)}</ul>}</Panel>}
      {tab==='requests'&&<Panel><Section title="Stock requests" description="Track requests from the app, WhatsApp or a call." button="New request" disabled={!data} onClick={()=>setForm({kind:'request'})}/>{!data?.dashboard.openRequests.length?<Empty text="No open requests."/>:<ul className="divide-y">{data.dashboard.openRequests.map(r=><li key={r.requestId} className="space-y-3 p-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{r.productName} · {r.qty}</p><Status value={r.status}/></div><p className="text-xs text-muted-foreground">{r.source||'APP'} · {r.notes}</p>{office&&<div className="flex flex-wrap gap-2">{r.status==='PENDING_APPROVAL'?<><Button disabled={busy} onClick={()=>void perform('purchase.approve',{requestId:r.requestId,decision:'APPROVE'})}>Approve</Button><Button disabled={busy} variant="outline" onClick={()=>void perform('purchase.approve',{requestId:r.requestId,decision:'REJECT'})}>Reject</Button></>:r.productId&&<><Button variant="outline" onClick={()=>setForm({kind:'order',productId:r.productId,requestId:r.requestId})}>Order from vendor</Button><Button variant="outline" onClick={()=>setForm({kind:'handover',productId:r.productId,requestId:r.requestId})}>Supply from stock</Button></>}</div>}</li>)}</ul>}</Panel>}
      {tab==='deliveries'&&<Panel><Section title="Purchases & deliveries" description="Only actual receipts increase stock. Opening stock is recorded separately." button="New purchase" disabled={!data} onClick={()=>setForm({kind:'order'})}/><div className="px-5 pt-4"><Button variant="outline" disabled={!data} onClick={()=>setForm({kind:'receive'})}>Delivery without an order</Button></div>{!data?.orders.length?<Empty text="No purchase orders recorded yet."/>:<ul className="divide-y">{data.orders.map(o=><li key={o.orderId} className="space-y-3 p-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{o.productName}</p><Status value={o.status}/></div><p className="text-xs text-muted-foreground">{o.orderId} · {c.vendors.find(v=>v.id===o.vendorId)?.name}</p><div className="grid grid-cols-3 gap-2 text-sm"><span>Ordered <strong>{o.qty}</strong></span><span>Received <strong>{o.received}</strong></span><span>Due <strong>{o.remaining} {o.uom}</strong></span></div>{o.remaining>0&&o.status!=='CANCELLED'&&<><Button disabled={busy} onClick={()=>setForm({kind:'receive',productId:o.productId,orderId:o.orderId})}>Receive delivery</Button>{noteField(o.orderId,'Reason to cancel remaining order')}<Button variant="outline" disabled={busy||!notes[o.orderId]} onClick={()=>void perform('order.cancel',{orderId:o.orderId,notes:notes[o.orderId]})}>Cancel remaining order</Button></>}</li>)}</ul>}</Panel>}
      {tab==='handovers'&&<Panel><Section title={office?'Sent to Salon Floor':'Confirm incoming stock'} description={office?'Pending quantities are reserved until the receiver confirms.':'Count the physical pieces before confirming receipt.'} button={office?'New handover':undefined} disabled={!data} onClick={()=>setForm({kind:'handover'})}/>{!pending.length?<Empty text="No handovers awaiting confirmation."/>:<ul className="divide-y">{pending.map(h=><li key={h.handoverId} className="space-y-3 p-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{h.productName} · {h.qty} {h.uom}</p><Status value="PENDING_CONFIRM"/></div><p className="text-xs text-muted-foreground break-words">{h.notes}</p>{!office&&<Field title="Quantity you counted"><TextInput type="number" min="0" step="any" value={recounts[h.handoverId]??''} onChange={e=>setRecounts({...recounts,[h.handoverId]:e.target.value})}/></Field>}{noteField(h.handoverId,office?'Reason for cancellation':'Note / count difference')}{office?<Button variant="outline" disabled={busy||!notes[h.handoverId]} onClick={()=>void perform('handover.cancel',{handoverId:h.handoverId,notes:notes[h.handoverId]})}>Cancel & release reservation</Button>:<Button disabled={busy||!online||!recounts[h.handoverId]} onClick={()=>void perform('stock.confirmHandover',{handoverId:h.handoverId,countedQty:Number(recounts[h.handoverId]),notes:notes[h.handoverId]||''})}>Confirm my count</Button>}<p className="text-xs text-muted-foreground">A different count keeps this pending. Agree the correction, then the sender can cancel and send a corrected handover.</p></li>)}</ul>}</Panel>}
      {(tab==='issue'||tab==='office')&&data&&<StockForm key={tab} form={{kind:tab==='office'?'office':'issue'}} data={data} office={office} admin={admin} busy={busy||loading||!online} onSubmit={perform}/>}
      {tab==='office'&&<Panel><Section title="Equipment in use" description="Assignments remain visible until returned or closed."/>{!data?.dashboard.assetsInUse.length?<Empty text="No equipment assigned yet."/>:data.dashboard.assetsInUse.map(a=><div key={a.assignmentId} className="space-y-3 border-t p-5"><p className="text-sm">{a.productName} · {a.qty} {a.uom} · {a.assignedTo}</p><div className="flex flex-wrap gap-2">{['RETURNED','DAMAGED','LOST','DISPOSED'].map(s=><Button key={s} variant="outline" disabled={busy} onClick={()=>void perform('asset.status',{assignmentId:a.assignmentId,status:s})}>{s.toLowerCase()}</Button>)}</div></div>)}</Panel>}
      {tab==='opening'&&<Panel><Section title={`${locationName} opening stock`} description="Record physical stock once, before the first transaction. Management approval makes it available." button="Add count" disabled={!data} onClick={()=>setForm({kind:'opening'})}/>{!openings.length?<Empty text="Start here: record the pieces already available at this location."/>:<ul className="divide-y">{openings.map(o=><li key={o.countId} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="text-sm font-medium">{o.productName}</p><p className="mt-1 text-sm">{o.qty} {o.uom}</p></div><Status value={o.status}/>{admin&&o.status==='PENDING'&&<div className="flex gap-2"><Button disabled={busy} onClick={()=>void perform('opening.approve',{countId:o.countId,decision:'APPROVE'})}>Approve</Button><Button variant="outline" disabled={busy} onClick={()=>void perform('opening.approve',{countId:o.countId,decision:'REJECT'})}>Reject</Button></div>}</li>)}</ul>}</Panel>}
      {tab==='history'&&<Panel><Section title="Movement history" description="Recent 500 movements across locations; this view shows your location." button="Export CSV" disabled={!history.length} onClick={exportHistory}/>{!history.length?<Empty text="Posted receipts, issues and corrections will appear here."/>:<ul className="divide-y">{history.map(h=><li key={h.txnId} className="space-y-2 p-5"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-medium">{c.products.find(p=>p.id===h.productId)?.name||h.productId} · {h.qty} {h.uom}</p><Status value={h.type}/></div><p className="text-xs text-muted-foreground">{new Date(h.date).toLocaleDateString('en-IN')} · {h.status} · {c.people.find(p=>p.id===h.personId)?.name||h.personId}</p><p className="text-xs break-words">{h.notes}</p></li>)}</ul>}</Panel>}
    </>}</div></div>
  </PageContainer></AppShell>;
}

function StockForm({form,data,office,admin,busy,onSubmit,onClose}:{form:FormSpec;data:Data;office:boolean;admin:boolean;busy:boolean;onSubmit:(action:AppsScriptAction,data:object)=>Promise<boolean>;onClose?:()=>void}) {
  const c=data.catalogue,kind=form.kind;
  const [productId,setProductId]=useState(form.productId||''),[qty,setQty]=useState(''),[person,setPerson]=useState(''),[category,setCategory]=useState(''),[vendor,setVendor]=useState(data.orders.find(o=>o.orderId===form.orderId)?.vendorId||''),[note,setNote]=useState('');
  const [source,setSource]=useState('APP'),[newName,setNewName]=useState(''),[approvedBy,setApprovedBy]=useState(''),[urgency,setUrgency]=useState('Normal'),[estimate,setEstimate]=useState(''),[correction,setCorrection]=useState('RETURN'),[sourceTxnId,setSourceTxnId]=useState('');
  const [invoice,setInvoice]=useState(''),[amount,setAmount]=useState(''),[photo,setPhoto]=useState<CapturedPhoto|null>(null),[productPhoto,setProductPhoto]=useState<CapturedPhoto|null>(null);
  const p=c.products.find(p=>p.id===productId),s=data.dashboard.stock.find(s=>s.productId===productId),loc=office?c.headOfficeLocationId:c.salonFloorLocationId,available=(office?s?.headOfficeAvailable:s?.salonFloorBalance)||0;
  const uom=kind==='receive'||kind==='order'?p?.purchaseUom:p?.uom,requiresPerson=['request','handover','issue','office'].includes(kind),people=c.people.filter(p=>kind!=='handover'||p.role==='ProductDistributor');
  const products=c.products.filter(p=>kind==='office'?p.productType==='Furniture':kind==='issue'?p.productType!=='Furniture':true);
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const common={productId,qty:Number(qty),notes:note};const action:AppsScriptAction=({request:'purchase.request',order:'order.create',receive:'stock.receive',handover:'stock.handover',issue:'stock.issue',office:'asset.issue',opening:'opening.submit',correction:'stock.adjust'} as const)[kind];let values:object=common;
    if(kind==='request')values={...common,newProductName:newName,requestedByUserId:person,source,urgency,estimatedValue:estimate?Number(estimate):undefined,approvedBy};
    if(kind==='order')values={...common,vendorId:vendor,requestId:form.requestId||''};
    if(kind==='receive')values={...common,vendorId:vendor,poId:form.orderId||'',invoiceNo:invoice,amount:amount?Number(amount):undefined,receivedByUserId:person,locationId:c.headOfficeLocationId,photo,productPhoto};
    if(kind==='handover')values={...common,toUserId:person,requestId:form.requestId||''};
    if(kind==='issue')values={productId,fromLocationId:loc,splits:[{qty:Number(qty),recipientUserId:person,categoryId:category,notes:note}]};
    if(kind==='office')values={...common,assignedTo:person,categoryId:category};
    if(kind==='opening')values={...common,locationId:loc};
    if(kind==='correction')values={...common,locationId:loc,kind:correction,sourceTxnId};
    if(await onSubmit(action,values)){setQty('');setNote('');setProductId('');setPhoto(null);setProductPhoto(null);}
  };
  return <Panel><Section title={LABEL[kind]} description={kind==='issue'?`Deducts from ${office?'Head Office':'Salon Floor'} stock.`:kind==='opening'?'Enter physical stock already present before using the application.':kind==='order'?'Creating an order does not change available stock.':kind==='office'?'Reusable equipment is tracked by assignment.':kind==='handover'?'Stock stays reserved until the receiver confirms.':kind==='receive'?'Enter only the quantity that actually arrived.':'Every movement keeps a reference and reason.'}/><form onSubmit={submit} className="p-5 sm:p-6"><fieldset disabled={busy} className="grid min-w-0 gap-5 sm:grid-cols-2 disabled:opacity-60">
    <Field title="Product" wide><Select required={!newName} value={productId} disabled={!!form.orderId||!!newName} onChange={e=>setProductId(e.target.value)}><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} ({kind==='receive'||kind==='order'?p.purchaseUom:p.uom})</option>)}</Select></Field>
    {kind==='request'&&<Field title="New product name (only if absent above)" wide><TextInput disabled={!!productId} value={newName} onChange={e=>setNewName(e.target.value)}/></Field>}
    {p&&['issue','handover','office'].includes(kind)&&<p className="rounded-xl bg-brand-subtle p-3 text-sm text-brand sm:col-span-2">Available: <strong>{available} {p.uom}</strong></p>}
    <Field title={`${kind==='opening'?'Physical count':kind==='receive'?'Quantity received':'Quantity'} ${uom?'('+uom+')':''}`}><TextInput required type="number" min={kind==='opening'?0:uom==='PCS'?1:0.001} step={uom==='PCS'?1:'any'} value={qty} onChange={e=>setQty(e.target.value)} max={['issue','handover','office'].includes(kind)?available:undefined}/></Field>
    {(requiresPerson||kind==='receive')&&<Field title={kind==='handover'?'Receiver':kind==='request'?'Requested by':kind==='office'?'Assigned to':kind==='receive'?'Received by (optional)':'Technician'}><Select required={requiresPerson} value={person} onChange={e=>setPerson(e.target.value)}><option value="">Select person</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field>}
    {['issue','office'].includes(kind)&&<Field title="Service / category"><Select required value={category} onChange={e=>setCategory(e.target.value)}><option value="">Select category</option>{c.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field>}
    {['order','receive'].includes(kind)&&<Field title="Vendor"><Select required disabled={!!form.orderId} value={vendor} onChange={e=>setVendor(e.target.value)}><option value="">Select vendor</option>{c.vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</Select></Field>}
    {kind==='request'&&<><Field title="Request source"><Select value={source} onChange={e=>setSource(e.target.value)}>{['APP','WHATSAPP','CALL'].map(s=><option key={s}>{s}</option>)}</Select></Field><Field title="Priority"><Select value={urgency} onChange={e=>setUrgency(e.target.value)}><option>Normal</option><option>Urgent</option></Select></Field><Field title="Estimated value (₹, optional)"><TextInput type="number" min="0" value={estimate} onChange={e=>setEstimate(e.target.value)}/></Field>{office&&<Field title={`Approved by (required from ₹${c.approvalThreshold})`}><TextInput value={approvedBy} onChange={e=>setApprovedBy(e.target.value)}/></Field>}</>}
    {kind==='receive'&&<><Field title="Invoice number"><TextInput value={invoice} onChange={e=>setInvoice(e.target.value)}/></Field><Field title="Amount for this product line (₹)"><TextInput type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><div className="sm:col-span-2"><p className="mb-2 text-sm">Bill photo</p><PhotoCapture onCapture={setPhoto} disabled={busy}/></div><div className="sm:col-span-2"><p className="mb-2 text-sm">Product photo (optional)</p><PhotoCapture onCapture={setProductPhoto} disabled={busy}/></div></>}
    {kind==='correction'&&<><Field title="Correction type"><Select value={correction} onChange={e=>setCorrection(e.target.value)}><option value="RETURN">Unused stock returned by technician</option><option value="DAMAGE">Damaged stock</option>{admin&&<><option value="COUNT_IN">Count adjustment — increase</option><option value="COUNT_OUT">Count adjustment — decrease</option></>}</Select></Field>{correction==='RETURN'&&<Field title="Original issue" wide><Select required value={sourceTxnId} onChange={e=>setSourceTxnId(e.target.value)}><option value="">Select issue</option>{data.history.filter(h=>h.type==='ISSUE'&&h.productId===productId&&h.locationId===loc&&h.status!=='VOID').map(h=><option key={h.txnId} value={h.txnId}>{h.txnId} · {h.qty} {h.uom}</option>)}</Select></Field>}</>}
    <Field title={kind==='request'||kind==='correction'?'Reason':'Note (optional)'} wide><TextInput required={kind==='request'||kind==='correction'} minLength={kind==='request'?3:undefined} value={note} onChange={e=>setNote(e.target.value)} placeholder="Purpose, shelf, room or details"/></Field><div className="flex flex-wrap gap-3 border-t pt-5 sm:col-span-2"><Button type="submit" className="min-h-11 flex-1 sm:flex-none" disabled={busy}>{busy&&<Loader2 className="size-4 animate-spin"/>}{LABEL[kind]}</Button>{onClose&&<Button type="button" variant="outline" onClick={onClose}>Cancel</Button>}</div>
  </fieldset></form></Panel>;
}
